правки по результатам ревью
4rl1996/queue-edu pull request #2
Opened 2022-10-25 10:40 UTC by 4rl1996

2022-11-01 14:35 UTC, nao4j requested changes

2022-11-01 14:35 UTC, nao4j commented on pom.xml
> +                        <phase>validate</phase>
Хитер конечно ) Но в целом это некорректный подход. Ты же это просто в качестве помощи локальному запуску используешь. Достаточно в README описать что для локального запуска требуется две команде мавену, первая запускает окружение, вторая запускает приложение

2022-11-01 14:35 UTC, nao4j commented on pom.xml
> +            <artifactId>spring-boot-starter-json</artifactId>
Зачем тебе целый стартер, который с собой еще и web тащит, если для работы `org.springframework.amqp.support.converter.Jackson2JsonMessageConverter` достаточно зависимости `jackson-databind`?

2022-11-01 14:35 UTC, nao4j commented on src/main/java/com/gmail/_4rl1996/queueedu/config/ConnectionFactoryConfig.java
> +    public RabbitTemplate rabbitTemplate(ConnectionFactory connectionFactory) {
Это тоже не нужно, все создается как только ты подключаешь стартер. Можно оставить только бин конвертера, потому что его автоконфигурация автоматом подтянет в чейн конвертации и использует для настройки темплейта.

2022-11-01 14:35 UTC, nao4j commented on src/main/java/com/gmail/_4rl1996/queueedu/config/ConnectionFactoryConfig.java
> +    public Queue getQueue() {
Зачем создан этот бин, если он ни где не используется? Если ты таким образом думал создать очередь, она и так создается как только продьюсер в нее шлет сообщение (если конфигом ребита разрешено)

2022-11-03 16:53 UTC, 4rl1996 commented on pom.xml
> +                        <phase>validate</phase>
Я раньше так и делал. Интересно было попробовать одной командой всё запустить.

2022-11-03 16:53 UTC, 4rl1996 commented on pom.xml
> +            <artifactId>spring-boot-starter-json</artifactId>
Исправил

2022-11-03 16:53 UTC, 4rl1996 commented on src/main/java/com/gmail/_4rl1996/queueedu/config/ConnectionFactoryConfig.java
> +    public RabbitTemplate rabbitTemplate(ConnectionFactory connectionFactory) {
Опять же из быстрого старта смотрел.

2022-11-03 16:53 UTC, 4rl1996 commented on src/main/java/com/gmail/_4rl1996/queueedu/config/ConnectionFactoryConfig.java
> +    public Queue getQueue() {
Я смотрел быстрый старт в доке к Spring AMQP, они там также делали, поэтому добавил. Действительно, работает и без него.

2022-11-10 18:05 UTC, merged